name: Deploy Release

on:
  workflow_dispatch:

jobs:
  build-mdl-sdk:
    name: Build MDL SDK
    uses: pablode/MDL-SDK/.github/workflows/main.yml@GA-2023.1.2
    with:
      cache-key-prefix: ${{ vars.MDL_SDK_CACHE_KEY_PREFIX }}

  build-usd2211:
    name: Build gatling for USD v22.11
    needs: build-mdl-sdk
    uses: ./.github/workflows/build-usd.yml
    with:
      usd-version: "22.11"
      mdl-sdk-cache-key-prefix: ${{ vars.MDL_SDK_CACHE_KEY_PREFIX }}
      upload-archives: true

  build-usd2311:
    name: Build gatling for USD v23.11
    needs: build-mdl-sdk
    uses: ./.github/workflows/build-usd.yml
    with:
      usd-version: "23.11"
      mdl-sdk-cache-key-prefix: ${{ vars.MDL_SDK_CACHE_KEY_PREFIX }}
      upload-archives: true

  build-houdini20:
    name: Build gatling for Houdini 20.0
    needs: build-mdl-sdk
    uses: ./.github/workflows/build-houdini20.yml
    with:
      mdl-sdk-cache-key-prefix: ${{ vars.MDL_SDK_CACHE_KEY_PREFIX }}

  deploy-release:
    name: Deploy Release
    needs: [build-usd2211, build-usd2311, build-houdini20]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts for USD v22.11
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build-usd2211.outputs.archive-name }}

      - name: Download artifacts for USD v23.11
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build-usd2311.outputs.archive-name }}

      - name: Download artifacts for Houdini 20.0
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build-houdini20.outputs.archive-name }}

      - name: Deploy draft release
        uses: softprops/action-gh-release@d4e8205d7e959a9107da6396278b2f1f07af0f9b
        with:
          name: "Version XXX"
          body: "TBD"
          files: |
            *.tar.gz
          fail_on_unmatched_files: true
          draft: true
