name: Validation Build

on:
  push:
    branches:
      - 'master'
      - 'dev'
    paths-ignore:
      - '**.md'
      - '**.glsl'

jobs:
  build-mdl-sdk:
    name: Build MDL SDK
    uses: pablode/MDL-SDK/.github/workflows/main.yml@GA-2023.1.2
    with:
      cache-key-prefix: ${{ vars.MDL_SDK_CACHE_KEY_PREFIX }}

  build-2403:
    name: Build gatling for USD v24.03 (Release)
    needs: build-mdl-sdk
    uses: ./.github/workflows/build-usd.yml
    with:
      usd-version: 24.03
      usd-python-version: 3.9
      mdl-sdk-cache-key-prefix: ${{ vars.MDL_SDK_CACHE_KEY_PREFIX }}
